"""Initial migration

Revision ID: 519a7da74bee
Revises: 
Create Date: 2025-09-20 15:42:12.615329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '519a7da74bee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kbr_gravimetry_v2',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('postfit', sa.Float(), nullable=True),
    sa.Column('observation_vector', sa.Float(), nullable=True),
    sa.Column('up_combined', sa.Float(), nullable=True),
    sa.Column('up_local', sa.Float(), nullable=True),
    sa.Column('up_common', sa.Float(), nullable=True),
    sa.Column('up_global', sa.Float(), nullable=True),
    sa.Column('latitude_A', sa.Float(), nullable=False),
    sa.Column('longitude_A', sa.Float(), nullable=False),
    sa.Column('altitude_A', sa.Float(), nullable=True),
    sa.Column('shadow_A', sa.Integer(), nullable=True),
    sa.Column('adtrack_A', sa.Integer(), nullable=True),
    sa.Column('latitude_B', sa.Float(), nullable=False),
    sa.Column('longitude_B', sa.Float(), nullable=False),
    sa.Column('altitude_B', sa.Float(), nullable=True),
    sa.Column('shadow_B', sa.Integer(), nullable=True),
    sa.Column('adtrack_B', sa.Integer(), nullable=True),
    sa.Column('longitude_MP', sa.Float(), nullable=False),
    sa.Column('latitude_MP', sa.Float(), nullable=False),
    sa.Column('altitude_MP', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('variant', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('release', sa.String(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kbr_gravimetry_v2_timestamp'), 'kbr_gravimetry_v2', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kbr_gravimetry_v2_timestamp'), table_name='kbr_gravimetry_v2')
    op.drop_table('kbr_gravimetry_v2')
    # ### end Alembic commands ###
