SATELLITE_FIELDS:
  - timestamp
  - postfit
  - observation_vector
  - up_combined
  - up_local
  - up_common
  - up_global
  - latitude_A
  - longitude_A
  - altitude_A
  - shadow_A
  #- irrelevant_A remove?
  - adtrack_A
  - latitude_B
  - longitude_B
  - altitude_B
  - shadow_B
  #- irrelevant_B remove?
  - adtrack_B
  - longitude_MP
  - latitude_MP
  - altitude_MP
  - latitude_MP
  - source
  - variant
  - label
  - release
